tz: GMT
tf: 'HH:mm'
notify-time: 10
update-interval: 2400
mysql:
    tables:
        refunds: 'refund'
        items: 'refund_detail'
    ip: localhost/ssrefund
    user: username
    password: password